version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install G++, CMake
          command: apt-get update && apt-get install -y g++ cmake libmysqlclient-dev libpq-dev

      # Build the project
      - run:
          name: Build project
          command: |
            mkdir build
            cd build
            cmake ..
            make

      # Run tests
      - run:
          name: Run tests
          command: |
            cd build
            ctest --output-on-failure


